# Cargo.toml
[package]
name = "rfbs"
version = "0.1.2"
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = false
lto = true