name: bot

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
  CARGO_LOCA: "Cargo.toml"

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  foo:
    runs-on: ubuntu-latest
    outputs:
          cargo_loc: ${{ steps.bar.outputs.cargo_loc }}
    steps:
      - 
        id: bar
        run: |
          echo cargo_loc=$CARGO_LOCA >> $GITHUB_OUTPUT
        shell: bash

  ready:
    needs:
      - foo
    uses: AUTOM77/Rust-Actions/.github/workflows/cargo-version.yml@main
    with:
      cargo_path: ${{ needs.foo.outputs.cargo_loc }}
    secrets: inherit

  push:
    needs:
      - ready
    uses: AUTOM77/Rust-Actions/.github/workflows/push-tag.yml@main
    with:
      version: v${{ needs.ready.outputs.version }}
    secrets: inherit

  publish:
    needs:
      - push
    uses: AUTOM77/Rust-Actions/.github/workflows/push-release.yml@main
    with:
      push_tag: ${{ needs.push.outputs.tag }}
      note: add ${{ needs.push.outputs.tag }}
    secrets: inherit