name: bot

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
  CARGO_LOCA: "Cargo.toml"
  ACTION: AUTOM77/Rust-Actions/.github/workflows

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  ready:
    uses: $ACTION/cargo-version.yml@main
    with:
      cargo_loc: "Cargo.toml"
    secrets: inherit

  push:
    needs:
      - ready
    uses: $ACTION/push-tag.yml@main
    with:
      version: v${{ needs.ready.outputs.version }}
    secrets: inherit

  publish:
    needs:
      - push
    uses: $ACTION/push-release.yml@main
    with:
      push_tag: ${{ needs.push.outputs.tag }}
      note: add ${{ needs.push.outputs.tag }}
    secrets: inherit